# Spring Boot
spring:
  application:
    name: WaRen Service Admin
    
# Spring Boot Port
server:
  port: 9001
  
dubbo:
  scan: 
    # Base packages to scan Dubbo Components (e.g., @Service, @Reference)
    basePackage: org.waren.admin.service
    
  # Dubbo Config properties
  ## ApplicationConfig Bean
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo

  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345

  ## RegistryConfig Bean
  registry:
    id: my-registry
    address: 127.0.0.1