# Spring Boot
spring:
  application:
    name: WaRen Service Admin
    
# Spring Boot Port
server:
  port: 9001

# Dubbo
dubbo:
  scan: 
    # Base packages to scan Dubbo Components (e.g., @Service, @Reference)
    basePackages: org.waren.admin.service
  application:
    id: waren-service-admin
    name: waren-service-admin
#    qos:
#      port: 22222
#      enable: true
  # ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  # RegistryConfig Bean
  registry:
    id: my-registry
    address: N/A
    
# Dubbo Health
management:
  health:
    dubbo:
      status:
        # StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        # StatusChecker Name extras (default : empty )
        extras: load,threadpool
