# Spring Boot
spring:
  application:
    name: WaRen Service Admin
    
# Spring Boot Port
server:
  port: 9001

# Dubbo
dubbo:
  scan: 
    # Base packages to scan Dubbo Components (e.g., @Service, @Reference)
    basePackages: org.waren.admin.service
  application:
    id: waren-service-admin
    name: waren-service-admin
#    qos:
#      port: 22222
#      enable: true
  # ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  # RegistryConfig Bean
  registry:
    id: my-registry
    address: N/A
    
# Dubbo Health
management:
  health:
    dubbo:
      status:
        # StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        # StatusChecker Name extras (default : empty )
        extras: load,threadpool
        
# Druid
druid:
    url: jdbc:mysql://192.168.1.11:10100/abc-dev?characterEncoding=utf-8
    driver-class: com.mysql.jdbc.Driver
    username: root
    password: kKpt3SjkQlT6g79wKSFFVI9y4leZHLAzhahzNuwvVRUQN/ljiPwIjyTlaGMujHtEqCBA45YAH/hnuj9wS2TDoA==
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMV1EoSTFHoH8n8PWbZW1U/qPQYpst8uOOu0R6967DJIX9g6MlDRJjpKK0jFCYeEa+MnLspcl9HvWuZUTkQeQZsCAwEAAQ==
    monitor:
      enabled: enabled
      druid-stat-view: /druid/*
      druid-web-stat-filter: /*
      allow: 127.0.0.1
      deny: 192.168.1.100
      login-username: admin
      login-password: 123456
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      reset-enable: false
